create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null,
  image_urls text[] not null default '{}',
  description text,
  category text,
  rating numeric default 4.5,
  review_count integer default 0,
  stock_quantity integer default 10,
  specifications jsonb default '{}',
  is_active boolean default true
);

create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  product_id bigint references products(id),
  product_title text,
  product_price numeric,
  quantity integer default 1,
  total_amount numeric,
  status text default 'Pending' -- Pending, Confirmed, Shipped, Delivered, Returned
);

create table reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_id bigint references products(id) not null,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  verified_purchase boolean default false
);
insert into storage.buckets (id, name, public)
select 'images', 'images', true
where not exists (
  select 1 from storage.buckets where id = 'images'
);
alter table products enable row level security;
alter table orders enable row level security;
alter table reviews enable row level security;
create policy "Public View Products"
on products for select
using (true);
create policy "Admin Manage Products"
on products for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
create policy "Public Create Orders"
on orders for insert
with check (true);
create policy "Admin View Orders"
on orders for select
using (auth.role() = 'authenticated');
create policy "Admin Update Orders"
on orders for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
create policy "Public View Images"
on storage.objects
for select
using (bucket_id = 'images');
create policy "Admin Upload Images"
on storage.objects
for insert
with check (bucket_id = 'images' and auth.role() = 'authenticated');
create policy "Admin Delete Images"
on storage.objects
for delete
using (auth.role() = 'authenticated');

create policy "Public View Reviews"
on reviews for select
using (true);
create policy "Public Create Reviews"
on reviews for insert
with check (true);

-- Insert sample products
INSERT INTO products (title, price, image_urls, description, category, rating, review_count, stock_quantity, specifications) VALUES
('iPhone 15 Pro Max', 450000, ARRAY['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400', 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400', 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400'], 'Latest iPhone with advanced camera system and A17 Pro chip', 'Smartphones', 4.8, 1250, 15, '{"Storage": "256GB", "Color": "Natural Titanium", "Display": "6.7-inch Super Retina XDR"}'),
('Samsung Galaxy S24 Ultra', 380000, ARRAY['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400', 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=400'], 'Premium Android smartphone with S Pen and 200MP camera', 'Smartphones', 4.7, 980, 20, '{"Storage": "512GB", "Color": "Titanium Black", "Display": "6.8-inch Dynamic AMOLED 2X"}'),
('MacBook Pro 16-inch', 650000, ARRAY['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400', 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'], 'Powerful laptop for professionals with M3 Max chip', 'Laptops', 4.9, 756, 8, '{"Processor": "Apple M3 Max", "RAM": "32GB", "Storage": "1TB SSD"}'),
('Dell XPS 13', 285000, ARRAY['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400', 'https://images.unsplash.com/photo-1587614295999-6c1a3262bc88?w=400'], 'Ultra-portable laptop with stunning display', 'Laptops', 4.6, 542, 12, '{"Processor": "Intel Core i7", "RAM": "16GB", "Storage": "512GB SSD"}'),
('Sony WH-1000XM5', 85000, ARRAY['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400', 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400'], 'Industry-leading noise canceling wireless headphones', 'Headphones', 4.8, 2100, 25, '{"Battery Life": "30 hours", "ANC": "Yes", "Connectivity": "Bluetooth 5.2"}'),
('AirPods Pro (2nd Gen)', 55000, ARRAY['https://images.unsplash.com/photo-1606220945770-b5b6c2c9bf1d?w=400', 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400'], 'Wireless earbuds with active noise cancellation', 'Headphones', 4.7, 3200, 30, '{"Battery Life": "6 hours", "ANC": "Yes", "Water Resistant": "IPX4"}'),
('iPad Pro 12.9-inch', 320000, ARRAY['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400', 'https://images.unsplash.com/photo-1544244615-868d2efc5887?w=400'], 'Powerful tablet for creators and professionals', 'Tablets', 4.8, 890, 10, '{"Display": "12.9-inch Liquid Retina XDR", "Chip": "M2", "Storage": "256GB"}'),
('Samsung Galaxy Tab S9', 180000, ARRAY['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400', 'https://images.unsplash.com/photo-1544244592-c48f8fac471c?w=400'], 'Premium Android tablet with S Pen included', 'Tablets', 4.5, 445, 18, '{"Display": "11-inch Dynamic AMOLED 2X", "Chip": "Snapdragon 8 Gen 2", "Storage": "128GB"}'),
('Nintendo Switch OLED', 95000, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400', 'https://images.unsplash.com/photo-1605902711834-8b11c3e3ef2f?w=400'], 'Handheld gaming console with vibrant OLED display', 'Gaming', 4.6, 1200, 22, '{"Display": "7-inch OLED", "Storage": "64GB", "Battery Life": "9 hours"}'),
('PlayStation 5', 185000, ARRAY['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400', 'https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=400'], 'Next-generation gaming console with 4K graphics', 'Gaming', 4.9, 3400, 5, '{"Storage": "825GB SSD", "Resolution": "4K", "HDR": "Yes"}'),
('Apple Watch Series 9', 125000, ARRAY['https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400', 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400'], 'Advanced smartwatch with health and fitness features', 'Wearables', 4.7, 1650, 16, '{"Display": "45mm Retina", "Health": "ECG, Blood Oxygen", "Battery": "18 hours"}'),
('Samsung Galaxy Watch 6', 75000, ARRAY['https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400', 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400'], 'Feature-rich smartwatch with comprehensive health tracking', 'Wearables', 4.4, 890, 20, '{"Display": "40mm Super AMOLED", "Health": "ECG, Blood Pressure", "Battery": "40 hours"}'),
('Nike Air Max 270', 25000, ARRAY['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400', 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400'], 'Comfortable running shoes with responsive cushioning', 'Clothing & Shoes', 4.6, 850, 35, '{"Size": "8-12", "Color": "Black/White", "Material": "Synthetic/Mesh"}'),
('Levi''s 501 Original Jeans', 12000, ARRAY['https://images.unsplash.com/photo-1542272604-787c3835535d?w=400', 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400'], 'Classic straight fit jeans with timeless style', 'Clothing & Shoes', 4.5, 1200, 28, '{"Size": "28-40", "Color": "Dark Wash", "Material": "100% Cotton"}'),
('KitchenAid Stand Mixer', 45000, ARRAY['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', 'https://images.unsplash.com/photo-1556909020-f6e7ad7d3136?w=400'], 'Professional 5-quart stand mixer for baking enthusiasts', 'Home & Kitchen', 4.8, 650, 12, '{"Capacity": "5 Quart", "Power": "325W", "Attachments": "3 Included"}'),
('Instant Pot Duo 7-in-1', 18000, ARRAY['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400'], 'Multi-cooker that replaces 7 kitchen appliances', 'Home & Kitchen', 4.7, 2100, 20, '{"Capacity": "6 Quart", "Functions": "7-in-1", "Material": "Stainless Steel"}'),
('The Psychology of Money', 2500, ARRAY['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400'], 'Timeless lessons on wealth, greed, and happiness', 'Books', 4.9, 3200, 45, '{"Author": "Morgan Housel", "Pages": "256", "Language": "English"}'),
('Atomic Habits', 2200, ARRAY['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400'], 'An Easy & Proven Way to Build Good Habits & Break Bad Ones', 'Books', 4.8, 4100, 38, '{"Author": "James Clear", "Pages": "320", "Language": "English"}'),
('Yoga Mat Premium', 3500, ARRAY['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400', 'https://images.unsplash.com/photo-1506629905607-0b5ab9a9e21a?w=400'], 'Non-slip exercise mat with carrying strap', 'Sports & Outdoors', 4.4, 780, 50, '{"Thickness": "6mm", "Material": "TPE", "Size": "68x24 inches"}'),
('Dumbbell Set 20kg', 8000, ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400'], 'Adjustable dumbbells for home workouts', 'Sports & Outdoors', 4.6, 920, 15, '{"Weight Range": "2-10kg each", "Material": "Cast Iron", "Includes": "2 Dumbbells"}'),
('The Ordinary Hyaluronic Acid', 1800, ARRAY['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400'], 'Hydrating serum for all skin types', 'Beauty & Personal Care', 4.5, 1600, 60, '{"Volume": "30ml", "Skin Type": "All", "Key Ingredient": "Hyaluronic Acid"}'),
('Cetaphil Gentle Skin Cleanser', 1200, ARRAY['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400'], 'Soap-free cleanser for sensitive skin', 'Beauty & Personal Care', 4.3, 2400, 75, '{"Volume": "473ml", "Skin Type": "Sensitive", "Fragrance": "Unscented"}'),
('LEGO Creator 3-in-1 Deep Sea Creatures', 4500, ARRAY['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400', 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400'], 'Buildable underwater adventure set', 'Toys & Games', 4.7, 1100, 25, '{"Pieces": "580", "Age": "7-12", "Theme": "Underwater"}'),
('Monopoly Classic Board Game', 3200, ARRAY['https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400', 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400'], 'The classic property trading board game', 'Toys & Games', 4.5, 1800, 30, '{"Players": "2-8", "Duration": "60-180 min", "Age": "8+"}'),
('Ergonomic Office Chair', 25000, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400', 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=400'], 'Adjustable office chair with lumbar support', 'Furniture', 4.6, 450, 8, '{"Material": "Mesh/Fabric", "Adjustable": "Yes", "Color": "Black"}'),
('Bookshelf 5-Tier', 15000, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400', 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=400'], 'Modern wooden bookshelf for home organization', 'Furniture', 4.4, 320, 12, '{"Shelves": "5", "Material": "MDF Wood", "Assembly": "Required"}'),
('Car Air Freshener Vent Clips', 800, ARRAY['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'], 'Fresh scent vent clips for car interior', 'Automotive', 4.2, 650, 100, '{"Scent": "New Car", "Pack": "2 clips", "Duration": "30 days"}'),
('Portable Car Jump Starter', 5500, ARRAY['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'], 'Emergency battery booster for vehicles', 'Automotive', 4.7, 380, 18, '{"Capacity": "10000mAh", "Peak Current": "800A", "USB Ports": "2"}');

-- Insert sample reviews
INSERT INTO reviews (product_id, customer_name, rating, comment, verified_purchase) VALUES
(1, 'Ahmed Khan', 5, 'Amazing camera quality and battery life. Worth every penny!', true),
(1, 'Sara Ahmed', 4, 'Great phone but expensive. Camera is outstanding though.', true),
(1, 'Muhammad Ali', 5, 'Best iPhone yet. The titanium build is premium.', true),
(2, 'Fatima Bibi', 5, 'S Pen is a game changer. Love the camera capabilities.', true),
(2, 'Omar Farooq', 4, 'Excellent Android phone with great features.', true),
(3, 'Zainab Malik', 5, 'Perfect for video editing. M3 chip is incredibly fast.', true),
(3, 'Hassan Raza', 5, 'Best laptop I have ever owned. Battery life is amazing.', true),
(4, 'Ayesha Khan', 4, 'Lightweight and powerful. Great for students.', true),
(5, 'Bilal Ahmed', 5, 'Noise cancellation is incredible. Perfect for work.', true),
(6, 'Maryam Ali', 4, 'Good sound quality but battery drains quickly.', true);
