-- 1. Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null,
  image_url text not null,
  description text,
  stock boolean default true
);

-- 2. Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  product_title text not null,
  product_price numeric not null,
  status text default 'Pending' -- Values: Pending, Confirmed, Delivered, Cancelled
);

-- 3. Enable Security (RLS)
alter table products enable row level security;
alter table orders enable row level security;

-- 4. Policies (Who can do what)
-- Everyone can view products
create policy "Public can view products" on products for select using (true);

-- Everyone can create an order (Submit form)
create policy "Public can create orders" on orders for insert with check (true);

-- Only YOU (Authenticated Admin) can view orders
-- Note: For this simplified code, we will allow public read on orders TEMPORARILY so you can build the admin panel easily. 
-- In production, you would lock this down.
create policy "Enable read access for all users" on orders for select using (true);
create policy "Enable update for all users" on orders for update using (true);

-- 5. Insert Dummy Data (So your site isn't empty)
insert into products (title, price, image_url, description) values
('Classic Leather Watch', 2499, 'https://images.unsplash.com/photo-1524592094714-0f0654e20314', 'Premium leather strap watch.'),
('Wireless Earbuds', 1850, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df', 'Noise cancelling with 20h battery.'),
('Men Denim Jacket', 3200, 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9', 'High quality denim for winter.');